version: "3.3"

services:
  front_end:
    image: nodenmap:latest
    ports:
      - "80:3000"
    networks:
      - nmap_net
    environment: 
      - DEBUG=app:*
      - TOKEN=${TOKEN}
    
networks:
    nmap_net:
